apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapi-deployment"
spec:
  replicas: 6
  selector:
    matchLabels:
      app: "coolapi"
  template:
    metadata:
      labels:
        app: "coolapi"
    spec:
      containers:
        - name: "coolapi"
          image: "acrpierrc007dridi.azurecr.io/coolapi:1.0.0"
          ports:
          - containerPort: 3000